# Configuration for Alacritty, the GPU enhanced terminal emulator.

TERM: xterm-256color

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true



# Colors (Tomorrow Night)
# colors:
#   # Default colors
#   primary:
#     background: '#1d1f21'
#     foreground: '#c5c8c6'

#   # Normal colors
#   normal:
#     black:   '#1d1f21'
#     red:     '#ac1a11'
#     green:   '#00A600'
#     yellow:  '#999900'
#     blue:    '#7EAAC7'
#     magenta: '#a327ad'
#     cyan:    '#00a6b2'
#     white:   '#bfbfbf'

#   # Bright colors
#   bright:
#     black:   '#666666'
#     red:     '#ad402a'
#     green:   '#00d900'
#     yellow:  '#e5e500'
#     blue:    '#001df4'
#     magenta: '#d235de'
#     cyan:    '#00e5e5'
#     white:   '#e5e5e5'

# Dim colors
#
# If the dim colors are not set, they will be calculated automatically based
# on the `normal` colors.
#dim:
#  black:   '#131415'
#  red:     '#864343'
#  green:   '#777c44'
#  yellow:  '#9e824c'
#  blue:    '#556a7d'
#  magenta: '#75617b'
#  cyan:    '#5b7d78'
#  white:   '#828482'



# Afterglow
# colors:
#   # Default colors
#   primary:
#     background: '#2c2c2c'
#     foreground: '#d6d6d6'

#     dim_foreground:    '#dbdbdb'
#     bright_foreground: '#d9d9d9'
#     dim_background:    '#202020' # not sure
#     bright_background: '#3a3a3a' # not sure

#   # Cursor colors
#   cursor:
#     text:   '#2c2c2c'
#     cursor: '#d9d9d9'

#   # Normal colors
#   normal:
#     black:   '#1c1c1c'
#     red:     '#bc5653'
#     green:   '#909d63'
#     yellow:  '#ebc17a'
#     blue:    '#7eaac7'
#     magenta: '#aa6292'
#     cyan:    '#86d3ce'
#     white:   '#cacaca'

#   # Bright colors
#   bright:
#     black:   '#636363'
#     red:     '#bc5653'
#     green:   '#909d63'
#     yellow:  '#ebc17a'
#     blue:    '#7eaac7'
#     magenta: '#aa6292'
#     cyan:    '#86d3ce'
#     white:   '#f7f7f7'

#   # Dim colors
#   dim:
#     black:   '#232323'
#     red:     '#74423f'
#     green:   '#5e6547'
#     yellow:  '#8b7653'
#     blue:    '#556b79'
#     magenta: '#6e4962'
#     cyan:    '#5c8482'
#     white:   '#828282'



# # Colors (Terminal.app)
# colors:
#   # Default colors
#   primary:
#     background: '#000000'
#     foreground: '#b6b6b6'

#   # Normal colors
#   normal:
#     black:   '#000000'
#     red:     '#990000'
#     green:   '#00a600'
#     yellow:  '#999900'
#     blue:    '#0000b2'
#     magenta: '#b200b2'
#     cyan:    '#00a6b2'
#     white:   '#bfbfbf'

#   # Bright colors
#   bright:
#     black:   '#666666'
#     red:     '#e50000'
#     green:   '#00d900'
#     yellow:  '#e5e500'
#     blue:    '#0000ff'
#     magenta: '#e500e5'
#     cyan:    '#00e5e5'
#     white:   '#e5e5e5'



# Colors (Solarized Light)
colors:
  # Default colors
  primary:
    background: '#fdf6e3' # base3
    foreground: '#657b83' # base00

  # Cursor colors
  cursor:
    text:   '#fdf6e3' # base3
    cursor: '#657b83' # base00

  # Normal colors
  normal:
    black:   '#073642' # base02
    red:     '#dc322f' # red
    green:   '#859900' # green
    yellow:  '#b58900' # yellow
    blue:    '#268bd2' # blue
    magenta: '#d33682' # magenta
    cyan:    '#2aa198' # cyan
    white:   '#eee8d5' # base2

  # Bright colors
  bright:
    black:   '#002b36' # base03
    red:     '#cb4b16' # orange
    green:   '#586e75' # base01
    yellow:  '#657b83' # base00
    blue:    '#839496' # base0
    magenta: '#6c71c4' # violet
    cyan:    '#93a1a1' # base1
    white:   '#fdf6e3' # base3



# scorcerer colors
# colors:
#   primary:
#     background: '#222222'
#     foreground: '#c2c2b0'

#   cursor:
#     text:   '#c2c2b0'
#     cursor: '#c2c2b0'

#   normal:
#     black:   '#111111'
#     red:     '#aa4450'
#     green:   '#719611'
#     yellow:  '#cc8800'
#     blue:    '#6688aa'
#     magenta: '#8f6f8f'
#     cyan:    '#528b8b'
#     white:   '#d3d3d3'

#   bright:
#     black:   '#181818'
#     red:     '#ff6a6a'
#     green:   '#b1d631'
#     yellow:  '#ff9800'
#     blue:    '#90b0d1'
#     magenta: '#8181a6'
#     cyan:    '#87ceeb'
#     white:   '#c1cdc1'



    # Bright and dim foreground colors
    #
    # The dimmed foreground color is calculated automatically if it is not present.
    # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
    # is `false`, the normal foreground color will be used.
    #dim_foreground: '#828482'
    #bright_foreground: '#eaeaea'

  # Cursor colors
  #
  # Colors which should be used to draw the terminal cursor.
  #
  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  #cursor:
  #  text: CellBackground
  #  cursor: CellForeground

  # Vi mode cursor colors
  #
  # Colors for the cursor when the vi mode is active.
  #
  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  #vi_mode_cursor:
  #  text: CellBackground
  #  cursor: CellForeground

  # Selection colors
  #
  # Colors which should be used to draw the selection area.
  #
  # Allowed values are CellForeground and CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  #selection:
  #  text: CellBackground
  #  background: CellForeground

  # Search colors
  #
  # Colors used for the search bar and match highlighting.
  #search:
    # Allowed values are CellForeground and CellBackground, which reference the
    # affected cell, or hexadecimal colors like #ff00ff.
    #matches:
    #  foreground: '#000000'
    #  background: '#ffffff'

    #bar:
    #  background: '#c5c8c6'
    #  foreground: '#1d1f21'

  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #
  # Example:
  #   `- { index: 16, color: '#ff00ff' }`
  #
  #indexed_colors: []
