#!/bin/bash

###############################################################################
# THIS SCRIPT IS A WIP. THERE ARE SOME ISSUES WITH STOWING FILES TO LOCATIONS
# WHERE DEFAULT FILES HAVE BEEN CREATED.
#
# Stow packages to their specific locations
# Run from within dotfiles directory
###############################################################################

set -eu

if [ -d ./git/ ]; then
  echo "stowing git stuff"
  stow --verbose=2 --target="$HOME" git
else
  echo "git package not found"
fi

# This may require a strategy of running stow with "--adopt", then git restoring
# the "adopted" file to it's state at the most recently committed change.
if [ -d ./VSCode/ ]; then
  echo "stowing VS Code stuff"
  stow \
    --verbose=2 \
    --target="$HOME/Library/Application Support/Code/User" \
    VSCode
else
  echo "VS Code package not found"
fi

if [ -d ./kitty/ ]; then
  echo "stowing kitty stuff"
  stow --verbose=2 --target="$HOME/.config/kitty" --ignore="themes" kitty
else
  echo "kitty package not found"
fi