#!/bin/bash

################################################################################
# Track and install extensions for vs code
#
# execution:
#    $ get-tokens [options]
#
# options:
#   -d
#   Dry-Run, no side effects
#
# TODO: check for installed ext before installing
# TODO: option to pass in non-default extension file.
################################################################################

readonly EXTENSION_FILE="$HOME/dotfiles/VSCode/extensions.txt"

D='false' # for dry-run

while getopts 'd' flag; do
  case "${flag}" in
    d) D='true' ;;
    *) echo "Unexpected option ${flag}" >&2; exit 1 ;;
  esac
done

if [ ! -f "$EXTENSION_FILE" ]; then
  echo "No extension file found at default location $EXTENSION_FILE."
  echo "Please create an extensions file."
  exit
fi

# Read extensions from file. Split string on newline characters.
IFS=$'\n' read -d '' -r -a EXTENSIONS < "$EXTENSION_FILE"

if ! command -v code &> /dev/null; then
  echo "It appears code is not installed or has not been added to PATH."
  echo "Install VS Code or add to PATH before installing extensions."
  exit
fi

for i in "${EXTENSIONS[@]}"; do
  echo "script is attempting to install $i"
  if [ "$D" = 'true' ]; then
    echo "Dry-run, extension $i will not be installed."
  else
    code --install-extension "$i"
  fi
done

# one off for setting up proper key repetition for vim vscode
# may require restarting vs code
installed_extensions=$(code --list-extensions)

for i in $installed_extensions; do
  if [ "$i" == "vscodevim.vim" ]; then
    if [ "$D" = 'true' ]; then
      echo "Dry-run."
    else
      echo "configuring vs code vim to allow key repetition"
      defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
    fi
  fi
done
