#! /bin/bash

# Track and install extensions for vs code
# TODO: check for installed ext before installing
# TODO: option for dry-run
# TODO: read extensions list from external file VSCode/extensions.txt

EXTENSIONS=(
  ms-python.python
  ms-python.vscode-pylance
  ms-toolsai.jupyter
  ms-toolsai.jupyter-keymap
  ms-toolsai.jupyter-renderers
  peterfh.linesinfostatusbar
  roscop.activefileinstatusbar
  ryuta46.multi-command
  stkb.rewrap
  streetsidesoftware.code-spell-checker
  vscodevim.vim
  wraith13.zoombar-vscode
)

if ! command -v code &> /dev/null; then
  echo "It appears code is not installed or has not been added to PATH."
  echo "Install VS Code or add to PATH before installing extensions."
  exit
fi

for i in "${EXTENSIONS[@]}"; do
  echo "script is attempting to install $i"
  code --install-extension "$i"
done

# one off for setting up proper key repetition for vim vscode
# may require restarting vs code
installed_extensions=$(code --list-extensions)

for i in $installed_extensions; do
  if [ "$i" == "vscodevim.vim" ]; then
    echo "configuring vs code vim to allow key repetition"
    defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
  fi
done
