#!/bin/bash

################################################################################
#
# Check if Tmux Plugin Manager is installed and clone if not
#
################################################################################


if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

